

def calculate_error():
    pass
